Repository sh7dm/vue-simpleicons, pull requests merged in 2018-12, with the labels that each got.

#14 [Enhancement] Add unit tests configuration
  .travis.yml
  jest.config.js
  package.json
  test/VueSimpleIcon.test.ts
  test/__snapshots__/VueSimpleIcon.test.ts.snap
  tsconfig.json
  yarn.lock
Labels: enhancement, help wanted

#18 Add commitlint configuration to enable commitlint
  commitlint.config.js
  package.json
  yarn.lock
Labels: bug

#17 Add `xmlns` attribute to generated SVGs
  src/VueSimpleIcon.ts
  test/__snapshots__/VueSimpleIcon.test.ts.snap
Labels: enhancement

#21 Update render error function
  playground/src/App.vue
  src/VueSimpleIcon.ts
  test/VueSimpleIcon.test.ts
  test/__snapshots__/VueSimpleIcon.test.ts.snap
Labels: enhancement

#20 Refactor icon generator (i.e. VueSimpleIcon component)
  src/VueSimpleIcon.ts
  test/VueSimpleIcon.test.ts
  test/__snapshots__/VueSimpleIcon.test.ts.snap
Labels: enhancement
